import "dotenv/config";
import { fileURLToPath } from "node:url";
import type { Redis } from "ioredis";
import { createLogger } from "@labs/logging";
import { createRedisClient, waitForRedis } from "./redis-client.js";
import { randomToken, sleep } from "./support.js";

const log = createLogger("lab22:redis-lock:basic-lock");

/**
 * `SET key value NX PX ttlMs` - atomic acquire-if-absent-with-expiration.
 * `value` is a fresh, unguessable ownership token generated by the caller,
 * never the lock key's own name and never shared across workers - it is
 * this token, not the key, that proves who currently owns the lock.
 */
export async function acquireLock(redis: Redis, key: string, ownerToken: string, ttlMs: number): Promise<boolean> {
  const result = await redis.set(key, ownerToken, "PX", ttlMs, "NX");
  return result === "OK";
}

/**
 * THE WRONG WAY, kept here only so it can be run and shown failing.
 * `GET` then `DEL` as two separate round trips is not atomic: between the
 * `GET` returning "yes, this is my token" and the `DEL` actually running,
 * the lock can expire and a completely different owner can acquire the same
 * key. The `DEL` then deletes the NEW owner's lock, not the caller's -
 * see demonstrateUnsafeCheckThenDeleteRace below for a real, reproducible
 * run of exactly this failure against a live Redis.
 */
export async function releaseLockUnsafeGetThenDel(redis: Redis, key: string, ownerToken: string): Promise<boolean> {
  const current = await redis.get(key);
  if (current !== ownerToken) {
    return false;
  }
  // --- unguarded gap: anything can happen to `key` between these two lines ---
  await redis.del(key);
  return true;
}

/**
 * THE CORRECT WAY: an atomic Lua script (`EVAL`) that checks the token AND
 * deletes the key in a single round trip Redis executes without
 * interruption. No other command can run against this key between the GET
 * and the DEL, because Redis executes the whole script as one atomic unit.
 */
const RELEASE_SCRIPT = `
if redis.call("GET", KEYS[1]) == ARGV[1] then
  return redis.call("DEL", KEYS[1])
else
  return 0
end
`;

export async function releaseLock(redis: Redis, key: string, ownerToken: string): Promise<boolean> {
  const result = await redis.eval(RELEASE_SCRIPT, 1, key, ownerToken);
  return result === 1;
}

// --- Demonstrations -------------------------------------------------------

export interface LockRaceResult {
  key: string;
  tokenA: string;
  tokenB: string;
  acquiredA: boolean;
  acquiredB: boolean;
  winner: "A" | "B" | "none";
}

/** Two workers race `acquireLock` for the SAME key at the same instant.
 * `SET ... NX` is atomic in Redis (single-threaded command execution), so
 * exactly one of these two concurrent calls can ever return true. */
export async function demonstrateLockRace(redis: Redis, key: string, ttlMs: number): Promise<LockRaceResult> {
  await redis.del(key);
  const tokenA = randomToken();
  const tokenB = randomToken();

  const [acquiredA, acquiredB] = await Promise.all([
    acquireLock(redis, key, tokenA, ttlMs),
    acquireLock(redis, key, tokenB, ttlMs),
  ]);

  const winner = acquiredA ? "A" : acquiredB ? "B" : "none";
  return { key, tokenA, tokenB, acquiredA, acquiredB, winner };
}

export interface WrongOwnerReleaseResult {
  key: string;
  realOwnerToken: string;
  wrongToken: string;
  wrongOwnerReleaseSucceeded: boolean;
  keySurvived: boolean;
  keyValueAfter: string | null;
}

/** A worker that does NOT hold the lock (wrong token) tries to release it.
 * The atomic Lua release must refuse, and the real owner's key/value must
 * survive untouched. */
export async function demonstrateWrongOwnerCannotRelease(
  redis: Redis,
  key: string,
  ttlMs: number,
): Promise<WrongOwnerReleaseResult> {
  await redis.del(key);
  const realOwnerToken = randomToken();
  const wrongToken = randomToken();

  const acquired = await acquireLock(redis, key, realOwnerToken, ttlMs);
  if (!acquired) {
    throw new Error("setup failure: could not acquire lock for the real owner");
  }

  const wrongOwnerReleaseSucceeded = await releaseLock(redis, key, wrongToken);
  const keyValueAfter = await redis.get(key);

  return {
    key,
    realOwnerToken,
    wrongToken,
    wrongOwnerReleaseSucceeded,
    keySurvived: keyValueAfter === realOwnerToken,
    keyValueAfter,
  };
}

export interface UnsafeCheckThenDeleteResult {
  key: string;
  tokenA: string;
  tokenB: string;
  acquiredBAfterExpiry: boolean;
  aDeletedBsLock: boolean;
  keyValueAfterAsRelease: string | null;
}

/**
 * Replays the exact failure `releaseLockUnsafeGetThenDel` is vulnerable to:
 * worker A's lock genuinely expires (short TTL, real wall-clock wait, no
 * mocking), worker B genuinely acquires the same key, and only THEN does A's
 * stale "GET already said it was mine" naive release logic run its `DEL`.
 * That `DEL` removes B's lock - a real, observable case of one worker
 * destroying another's active lock because "check" and "delete" were two
 * separate, non-atomic Redis calls.
 */
export async function demonstrateUnsafeCheckThenDeleteRace(
  redis: Redis,
  key: string,
): Promise<UnsafeCheckThenDeleteResult> {
  await redis.del(key);
  const shortTtlMs = 100;
  const tokenA = randomToken();
  await acquireLock(redis, key, tokenA, shortTtlMs);

  // Naive release, step 1: GET and compare (this is the part of the naive
  // function that "passes" - A really did hold this key a moment ago).
  const seenByA = await redis.get(key);
  const aBelievesItOwnsTheKey = seenByA === tokenA;

  // The unguarded gap: A's lock expires for real, and B genuinely acquires
  // the same key before A's naive release gets to step 2 (DEL).
  await sleep(shortTtlMs + 50);
  const tokenB = randomToken();
  const acquiredBAfterExpiry = await acquireLock(redis, key, tokenB, 5_000);

  // Naive release, step 2: DEL, unconditionally, because step 1 already
  // "confirmed" ownership - except the key underneath has changed owners.
  let aDeletedBsLock = false;
  if (aBelievesItOwnsTheKey) {
    const beforeDelete = await redis.get(key);
    await redis.del(key);
    aDeletedBsLock = beforeDelete === tokenB;
  }

  const keyValueAfterAsRelease = await redis.get(key);

  return { key, tokenA, tokenB, acquiredBAfterExpiry, aDeletedBsLock, keyValueAfterAsRelease };
}

async function main(): Promise<void> {
  const redis = createRedisClient();
  await waitForRedis(redis);
  try {
    const raceKey = "lock:demo:basic-lock-race";
    const race = await demonstrateLockRace(redis, raceKey, 5_000);
    log.info(race, "two workers raced SET NX PX on the same key - exactly one acquired it");
    await releaseLock(redis, raceKey, race.winner === "A" ? race.tokenA : race.tokenB);

    const wrongOwnerKey = "lock:demo:wrong-owner-release";
    const wrongOwner = await demonstrateWrongOwnerCannotRelease(redis, wrongOwnerKey, 5_000);
    log.info(wrongOwner, "a worker with the wrong token tried to release the lock");
    await releaseLock(redis, wrongOwnerKey, wrongOwner.realOwnerToken);

    const unsafeKey = "lock:demo:unsafe-get-then-del";
    const unsafe = await demonstrateUnsafeCheckThenDeleteRace(redis, unsafeKey);
    log.warn(unsafe, "naive GET-then-DEL release deleted a DIFFERENT owner's lock after expiry+reacquire");
  } finally {
    redis.disconnect();
  }
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((error: unknown) => {
    log.error({ err: error }, "basic-lock scenario failed");
    process.exit(1);
  });
}
