import { createLogger } from "@labs/logging";
import { primaryDb, primaryPool, waitForDatabase as waitForPrimary } from "../db/primary-client.js";
import { replicaPool, waitForDatabase as waitForReplica } from "../db/replica-client.js";
import { widgets } from "../db/schema.js";

const log = createLogger("lab24:scenario:inspect-wal-and-lsn");

const BATCH_SIZE = 50;

interface ReplicationStatRow {
  application_name: string;
  state: string;
  sent_lsn: string;
  write_lsn: string;
  flush_lsn: string;
  replay_lsn: string;
  sync_state: string;
}

/**
 * Makes the WAL-shipping-and-replay mechanism concrete with real LSN
 * values, not just named concepts: read pg_current_wal_lsn() on the primary
 * before and after a batch of writes and show it advancing, then read the
 * replica's own replay position and the primary's view of that same
 * replica via pg_stat_replication.
 */
async function main() {
  await waitForPrimary(primaryPool);
  await waitForReplica(replicaPool);

  const before = await primaryPool.query<{ lsn: string }>("SELECT pg_current_wal_lsn() AS lsn");
  const lsnBefore = before.rows[0]?.lsn;
  log.info({ lsnBefore }, "primary WAL position BEFORE the write batch");

  const rows = Array.from({ length: BATCH_SIZE }, (_, i) => ({
    name: `wal-lsn-probe-${i + 1}`,
    value: i + 1,
  }));
  await primaryDb.insert(widgets).values(rows);

  const after = await primaryPool.query<{ lsn: string }>("SELECT pg_current_wal_lsn() AS lsn");
  const lsnAfter = after.rows[0]?.lsn;
  log.info({ lsnAfter, rowsWritten: rows.length }, "primary WAL position AFTER the write batch");

  const diff = await primaryPool.query<{ bytes: string }>(
    "SELECT pg_wal_lsn_diff($1, $2) AS bytes",
    [lsnAfter, lsnBefore],
  );
  log.info(
    { walBytesAdvanced: diff.rows[0]?.bytes },
    "pg_wal_lsn_diff(after, before) - bytes of WAL generated by this batch",
  );

  const replicationStats = await primaryPool.query<ReplicationStatRow>(
    `SELECT application_name, state, sent_lsn, write_lsn, flush_lsn, replay_lsn, sync_state
     FROM pg_stat_replication`,
  );
  log.info(
    { connectedReplicas: replicationStats.rowCount, rows: replicationStats.rows },
    "pg_stat_replication on the primary - the primary's own view of every connected standby",
  );

  const replicaReplay = await replicaPool.query<{ replay_lsn: string; in_recovery: boolean }>(
    "SELECT pg_last_wal_replay_lsn() AS replay_lsn, pg_is_in_recovery() AS in_recovery",
  );
  log.info(replicaReplay.rows[0], "replica's own view of its WAL replay position");

  await primaryPool.end();
  await replicaPool.end();
}

main().catch((error: unknown) => {
  log.error({ err: error }, "inspect-wal-and-lsn failed");
  process.exit(1);
});
