name: lab20-sagas-and-distributed-workflows

services:
  postgres:
    image: postgres:16-alpine
    container_name: lab20-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lab20}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lab20}
      POSTGRES_DB: ${POSTGRES_DB:-lab20}
    ports:
      - "${POSTGRES_PORT:-5420}:5432"
    volumes:
      - lab20_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lab20} -d ${POSTGRES_DB:-lab20}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgweb:
    image: sosedoff/pgweb
    container_name: lab20-pgweb
    environment:
      PGWEB_DATABASE_URL: postgres://${POSTGRES_USER:-lab20}:${POSTGRES_PASSWORD:-lab20}@postgres:5432/${POSTGRES_DB:-lab20}?sslmode=disable
    ports:
      - "${PGWEB_PORT:-8420}:8081"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  lab20_postgres_data:
